In [161]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
import warnings 
warnings.filterwarnings("ignore")

In [162]:
df = sns.load_dataset("titanic")

In [163]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [164]:
df.shape

(891, 15)

In [165]:
df.describe()

survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [166]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [167]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [168]:
df.drop(["adult_male" , "deck" , "who" , "class" , "alive" , "embark_town"] ,axis=1 , inplace=True)

In [169]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  891 non-null    int64  
 1   pclass    891 non-null    int64  
 2   sex       891 non-null    object 
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64  
 5   parch     891 non-null    int64  
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object 
 8   alone     891 non-null    bool   
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 56.7+ KB


In [170]:
df["age"].fillna(df["age"].mean() , inplace=True)


In [171]:
df.drop_duplicates(inplace=True)

In [172]:
df.dropna(subset=["embarked"], inplace=True)

In [173]:
from sklearn.preprocessing import LabelEncoder
encode = LabelEncoder()

In [174]:
df["sex"] = encode.fit_transform(df["sex"])
df["embarked"] = encode.fit_transform(df["embarked"]) # c = 0 , q = 1 , s =2 

In [175]:
df["alone"] = encode.fit_transform(df["alone"])

In [176]:
df.head()

survived  pclass  sex   age  sibsp  parch     fare  embarked  alone
0         0       3    1  22.0      1      0   7.2500         2      0
1         1       1    0  38.0      1      0  71.2833         0      0
2         1       3    0  26.0      0      0   7.9250         2      1
3         1       1    0  35.0      1      0  53.1000         2      0
4         0       3    1  35.0      0      0   8.0500         2      1

In [177]:
X = df.drop("survived" , axis=1)
y = df["survived"]

In [178]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [179]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [180]:
model.fit(X_train , y_train)

LogisticRegression()

In [181]:
y_pred = model.predict(X_test)

In [182]:
y_pred

array([1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0], dtype=int64)

In [183]:
from sklearn.metrics import accuracy_score , confusion_matrix , classification_report

In [184]:
accuracy_score(y_test , y_pred)

0.7564102564102564

In [185]:
confusion_matrix(y_test,y_pred)

array([[75, 16],
       [22, 43]], dtype=int64)

In [186]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.77      0.82      0.80        91
           1       0.73      0.66      0.69        65

    accuracy                           0.76       156
   macro avg       0.75      0.74      0.75       156
weighted avg       0.75      0.76      0.75       156



In [187]:
# for knn feature scalling is important because it calculates k nearest neighbour
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [188]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

In [189]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier()

In [190]:
model.fit(X_train_scaled , y_train)

KNeighborsClassifier()

In [191]:
y_pred = model.predict(X_test_scaled)

In [192]:
accuracy_score(y_test , y_pred)

0.75

In [193]:
confusion_matrix(y_test , y_pred)

array([[80, 11],
       [28, 37]], dtype=int64)

In [194]:
print(classification_report(y_test , y_pred))

              precision    recall  f1-score   support

           0       0.74      0.88      0.80        91
           1       0.77      0.57      0.65        65

    accuracy                           0.75       156
   macro avg       0.76      0.72      0.73       156
weighted avg       0.75      0.75      0.74       156



In [195]:
from sklearn.naive_bayes import GaussianNB 
model = GaussianNB()

In [196]:
model.fit(X_train , y_train)

GaussianNB()

In [197]:
y_pred = model.predict(X_test)

In [198]:
accuracy_score(y_test , y_pred)

0.7628205128205128

In [199]:
confusion_matrix(y_test , y_pred)

array([[78, 13],
       [24, 41]], dtype=int64)

In [200]:
print(classification_report(y_test , y_pred))

              precision    recall  f1-score   support

           0       0.76      0.86      0.81        91
           1       0.76      0.63      0.69        65

    accuracy                           0.76       156
   macro avg       0.76      0.74      0.75       156
weighted avg       0.76      0.76      0.76       156



In [201]:
from sklearn.tree import DecisionTreeClassifier 
model = DecisionTreeClassifier()

In [202]:
model.fit(X_train , y_train)

DecisionTreeClassifier()

In [203]:
y_pred = model.predict(X_test)

In [204]:
accuracy_score(y_test , y_pred)

0.7435897435897436

In [205]:
print(classification_report(y_test , y_pred))

              precision    recall  f1-score   support

           0       0.76      0.81      0.79        91
           1       0.71      0.65      0.68        65

    accuracy                           0.74       156
   macro avg       0.74      0.73      0.73       156
weighted avg       0.74      0.74      0.74       156



In [206]:
model = DecisionTreeClassifier(random_state=42)

In [207]:
model.fit(X_train_scaled , y_train)

DecisionTreeClassifier(random_state=42)

In [208]:
y_pred = model.predict(X_test_scaled)

In [209]:
accuracy_score(y_test , y_pred)

0.7692307692307693

In [210]:
print(classification_report(y_test , y_pred))

              precision    recall  f1-score   support

           0       0.75      0.90      0.82        91
           1       0.81      0.58      0.68        65

    accuracy                           0.77       156
   macro avg       0.78      0.74      0.75       156
weighted avg       0.78      0.77      0.76       156



In [211]:
from sklearn.svm import SVC
model = SVC(kernel="rbf")

In [212]:
model.fit(X_train_scaled , y_train)

SVC()

In [213]:
y_pred = model.predict(X_test_scaled)

In [214]:
accuracy_score(y_test  , y_pred)

0.7692307692307693

In [215]:
print(classification_report(y_test , y_pred))

              precision    recall  f1-score   support

           0       0.76      0.88      0.82        91
           1       0.78      0.62      0.69        65

    accuracy                           0.77       156
   macro avg       0.77      0.75      0.75       156
weighted avg       0.77      0.77      0.76       156

