In [1]:
import numpy as np 
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt 

In [2]:
df = pd.read_csv('train.txt' , sep=';' , header=None , names=['Text' , 'Emotion'])

In [3]:
df.head()

Text  Emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [4]:
emotions_values = df['Emotion'].unique()

In [5]:
emotions = { emotions_values[i]:i for i in range(len(emotions_values))}

In [6]:
emotions

{'sadness': 0, 'anger': 1, 'love': 2, 'surprise': 3, 'fear': 4, 'joy': 5}

In [7]:
df['Emotion'] = df['Emotion'].map(emotions)

In [8]:
df['Text'] = df['Text'].apply(lambda txt : txt.lower())

In [9]:
# remove punctuations 
import string 
def remove_punctuations (txt):
    return txt.translate(str.maketrans(' ' , ' ' , string.punctuation))

In [10]:
df['Text'] = df['Text'].apply(remove_punctuations)

In [11]:
# remove no .
def remove_num(txt):
    new = "" 
    for i in txt :
        if not i.isdigit():
            new+=i
    return new 
df["Text"] = df['Text'].apply(remove_num)

In [12]:
# remove emojis 
def remove_emoji(txt):
    new = ""
    for i in txt :
        if i.isascii():
            new += i 
    return new 

df['Text'] = df['Text'].apply(remove_emoji)

In [13]:
import nltk 

In [14]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [15]:
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ashif\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ashif\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [16]:
stop_words = set(stopwords.words('english'))

In [17]:
def remove_stopwords (txt):
    words = txt.split()
    cleaned = []
    for i in words :
        if not i in stop_words:
            cleaned.append(i)
    return ' '.join(cleaned)


In [18]:
df['Text'] = df['Text'].apply(remove_stopwords)

In [20]:
from sklearn.feature_extraction.text import CountVectorizer
vc = CountVectorizer(max_features=5)
X = vc.fit_transform(df['Text'])

print(f'vocablary : {vc.get_feature_names_out()}')
print(f'\nBow matrix : {X.toarray()}')

vocablary : ['feel' 'feeling' 'im' 'like' 'really']

Bow matrix : [[1 0 0 0 0]
 [0 1 0 0 0]
 [1 0 1 0 0]
 ...
 [1 0 0 0 0]
 [1 0 1 1 0]
 [1 0 0 0 0]]
