In [1]:
#numpy is written in c  upto 50x faster than list

"""
                    List        vs           Arrays
nature              any data type            only same data type 
performance         slower                   faster 
memory efficiency   low                      high
vector operation    manual                   easy and fast
"""



'\n                    List        vs           Arrays\nnature              any data type            only same data type \nperformance         slower                   faster \nmemory efficiency   low                      high\nvector operation    manual                   easy and fast\n'

In [2]:
import numpy as np

In [3]:
arr = np.array([1, 2 , 3 , 4 ,5 ,6 ,7 ,8 ])
print(arr)

[1 2 3 4 5 6 7 8]


In [ ]:
a = [1 , 3 ,4 ,"Ash"]
newAr = np.array(a)
newAr # array(['1', '3', '4', 'Ash'], dtype='<U11')

array(['1', '3', '4', 'Ash'], dtype='<U11')

In [5]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
# move than 2 dimension is known as tensers 


**Array generation functions**

In [8]:
np.arange(1, 11) # 1 to 10 array created 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np.arange(1, 10 , 2) # start , stop ,step

array([1, 3, 5, 7, 9])

In [10]:
#! Zeroes creation
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros((4 ,6)) # 4 row 6 col

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [14]:
arr = np.ones((5 , 8))

In [15]:
arr

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [16]:
arr = np.linspace(1 , 10 , 2) # gives linearly spaced list 1, 10 is output for 2 
arr 

array([ 1., 10.])

In [20]:
arr = np.linspace(1 , 10 , 4)
arr

array([ 1.,  4.,  7., 10.])

**Random generation function**

In [ ]:
arr = np.random.rand(10) # returns 10 random number from 0 to 1 (normalization)
arr
arr = np.random.randn(10) # return from -3 to 3 (standarization)
arr

array([-1.23120045, -2.0305553 , -0.55285854, -0.70340108, -0.00917999,
        2.05682859, -1.56098239, -0.73309624, -1.79788859,  1.17066122])

In [23]:
arr = np.random.randint(10 , 20 , 3) # low , high , no. of element wants 

In [24]:
arr

array([16, 10, 14])

**Array attributes**

In [25]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [26]:
arr.shape

(3, 3)

In [27]:
arr.size

9

In [28]:
arr.dtype

dtype('int32')

**Array Methods**

In [29]:
arr.min()

1

In [30]:
arr.max()

9

In [31]:
arr.sum()

45

In [32]:
"""
axis 
       |
 1 ----|->
       |
       0 
"""
np.sum(arr , axis=0)

array([12, 15, 18])

In [33]:
np.sum(arr , axis=1)

array([ 6, 15, 24])

In [35]:
arr.mean()

5.0

In [36]:
arr.std()

2.581988897471611

In [37]:
arr.argmax()

8

In [38]:
arr.argmin()

0

**Reshaping and Resizing**

In [39]:
arr = np.arange(1, 31)

In [40]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [41]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [42]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [43]:
arr.resize(6,5)

In [44]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])