**Numpy indexing and slicing of vectors**

In [27]:
import numpy as np

In [28]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [29]:
arr[4]

15

In [30]:
arr[1:4]

array([12, 13, 14])

In [31]:
arr[1:10:2]

array([12, 14, 16, 18, 20])

***Numpy Indexing & Slicing of Matrix***

In [32]:
arr = np.arange(1,31).reshape(6,5)

In [33]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [34]:
arr[0]

array([1, 2, 3, 4, 5])

In [35]:
arr[0][4]
arr[0,4]

5

In [36]:
arr[0:3]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [37]:
arr[0:3]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [38]:
arr[0:2 , 1:3]

array([[2, 3],
       [7, 8]])

In [39]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [40]:
arr[3: , 3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

**Boolean Indexing**

In [41]:
bool_index= arr%2 == 0
bool_index

array([[False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

In [42]:
arr = arr[bool_index]

In [43]:
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])