**Array Operations**

In [26]:
import numpy as np
arr1 = np.arange(1,31)
arr2 = np.arange(31,61)

In [27]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [28]:
arr2

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60])

In [29]:
#! Arithmetic operations 
# broadcasting happen
arr1+arr2
# - , * ,  / , // , and all

array([32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64,
       66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90])

**Deeep & Shallow Copy**

In [30]:
ar1 = np.arange(1,21)

In [31]:
ar2 = ar1[:5]

In [32]:
ar2

array([1, 2, 3, 4, 5])

In [33]:
ar2=ar2+10

In [34]:
ar1 # no change due to shallow copy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [35]:
b = ar1.copy()

In [36]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [37]:
b = ar1 # deep copy

**Multiplication of Matrix**

In [41]:
A = np.arange(1,7).reshape(2,3)
B = np.arange(7,13).reshape(3,2)


In [43]:
A @ B # according to maths

array([[ 58,  64],
       [139, 154]])

In [44]:
# also
np.dot(A , B)

array([[ 58,  64],
       [139, 154]])

In [45]:
# transpose of array - row become column
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

***Advance array manipulation***

In [47]:
#! Stacking of array
a = np.arange(1,5)
b = np.arange(6,10)

In [48]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [49]:
np.hstack((a,b))

array([1, 2, 3, 4, 6, 7, 8, 9])

In [50]:
np.column_stack((a,b))

array([[1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

Split

In [54]:
B = np.arange(1,31).reshape(3,10)
np.hsplit(B,2)

[array([[ 1,  2,  3,  4,  5],
        [11, 12, 13, 14, 15],
        [21, 22, 23, 24, 25]]),
 array([[ 6,  7,  8,  9, 10],
        [16, 17, 18, 19, 20],
        [26, 27, 28, 29, 30]])]

In [56]:
np.hsplit(B , 5)

[array([[ 1,  2],
        [11, 12],
        [21, 22]]),
 array([[ 3,  4],
        [13, 14],
        [23, 24]]),
 array([[ 5,  6],
        [15, 16],
        [25, 26]]),
 array([[ 7,  8],
        [17, 18],
        [27, 28]]),
 array([[ 9, 10],
        [19, 20],
        [29, 30]])]